# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ test/githubActions ]
  pull_request:
    branches: [ test/githubActions ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test 
      run: npm ci
    - name: Test operator
      run: cd rollup-operator; npm ci; ls;
    - name: Test operator_js
      run: cd rollup-operator; ls; npm run test:js-pob
    - name: Test contracts
      run: npm run test:contracts
